In [2]:
def my_function(x, y):
    pass

In [3]:
def my_sq(x):
    return x ** 2

In [4]:
my_sq(2)

4

In [5]:
my_sq(4)

16

In [8]:
assert my_sq(4) == 16 # testing the function (if false, returns error)

In [9]:
assert my_sq(4) == 15

AssertionError: 

In [10]:
def avg_2(x, y):
    return (x + y) / 2

In [11]:
avg_2(10, 20)

15.0

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame({
    'a' : [10, 20, 30],
    'b' : [20, 30, 40]
})

In [19]:
df

a   b
0  10  20
1  20  30
2  30  40

In [20]:
df['a'] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [21]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [22]:
def my_exp(x, e):
    return x ** e

In [23]:
my_exp(2, 10)

1024

In [28]:
df['a'].apply(my_exp, e=4) # **kwrds grants access to all the function parameters

0     10000
1    160000
2    810000
Name: a, dtype: int64

In [29]:
def print_me(x):
    print(x)

In [30]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [31]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [33]:
df

a   b
0  10  20
1  20  30
2  30  40

In [32]:
df.apply(avg_3)

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [39]:
import numpy as np

In [40]:
def avg_3_apply(col):
    return np.mean(col)

In [41]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [44]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [45]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [47]:
df

a   b
0  10  20
1  20  30
2  30  40

In [48]:
df.apply(avg_3_apply, axis='columns')

IndexError: index out of bounds

In [50]:
df['a'].mean()

20.0

In [51]:
df['a'] + df['b']

0    30
1    50
2    70
dtype: int64

In [52]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [53]:
df

a   b
0  10  20
1  20  30
2  30  40

In [54]:
avg_2_mod(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [57]:
avg_2_mod_vec = np.vectorize(avg_2_mod) # vectorizes the function so its able to work for each value of a vector

In [60]:
df

a   b
0  10  20
1  20  30
2  30  40

In [58]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [61]:
@np.vectorize
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [62]:
avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [67]:
import numba

In [68]:
@numba.vectorize
def avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [69]:
avg_2_mod_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [71]:
%%timeit
avg_2(df['a'], df['b'])

180 µs ± 3.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [72]:
%%timeit
avg_2_mod(df['a'], df['b'])

50.3 µs ± 271 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [73]:
%%timeit
avg_2_mod_numba(df['a'].values, df['b'].values)

4.5 µs ± 18.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
